name: wf_pr_develop
on:
  pull_request:
    branches:
      - develop
jobs:
  pr_dev_job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6
      - name: Install Project Dependencies
        run: npm ci
      - name: Lint HTML Files
        run: npm run htmlhint
      - name: Lint CSS Files
        run: npm run stylelint
      - name: Build Website
        run: npm run build
      - name: Build Docker Image
        run: docker image build . -t abdullahaskari17/spring26w13at1:v01
      - name: See the Image
        run: docker image ls
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Image on the Docker Hub
        run: docker image push abdullahaskari17/spring26w13at1:v01